name: Tests

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run tools tests
              uses: make test_tools_verbose